version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'webserver-apache'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mysql:
    build: ./bin/mysql
    container_name: 'database-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: d8_docker
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  drupal:
    image: drupal:latest
    ports:
      - 80:80
    volumes: 
      - ${DOCUMENT_ROOT-./www/web}:/var/www/html
    depends_on:
      - mysql
    restart: always